apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  namespace: monitoring
data:
  backend-alerts.yml: |
    groups:
    - name: backend-alerts
      rules:
      - alert: BackendDown
        expr: up{job="backend"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Backend service is DOWN"
          description: "Prometheus cannot scrape backend for 30 seconds."

      - alert: BackendHighCPU
        expr: rate(process_cpu_seconds_total[1m]) > 0.5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on backend"
          description: "Backend CPU usage exceeded 0.5 cores."

      - alert: BackendHighMemory
        expr: process_resident_memory_bytes > 2e+08
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on backend"
          description: "Backend memory usage exceeded 200MB."
